version: '3.3'

services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml